<?php require 'header.inc'; ?>

<?php if ($errors) : ?>
	<div class="alert alert-danger" role="alert">
<?php foreach ($errors as $error) : ?>
		<?=htmlspecialchars($error, ENT_QUOTES, 'utf-8');?><br/>
<?php endforeach; ?>
	</div>
<?php endif; ?>

	<main class="container flex-grow-1 py-3">
		<form method="post" action="/submit" enctype="multipart/form-data">
			<div class="form-check">
				<label class="form-check-label">
					<input class="form-check-input" type="radio" name="data[present]" id="absent" value="0" required="required"<?php if ($data['present'] === 0) : ?> checked="checked"<?php endif; ?>>
					Объект <strong>отсутствует</strong> в «Чистилище»
				</label>
			</div>
			<div class="form-check">
				<label class="form-check-label">
					<input class="form-check-input" type="radio" name="data[present]" id="present" value="1" required="required"<?php if ($data['present'] === 1) : ?> checked="checked"<?php endif; ?>>
					Объект <strong>присутствует</strong> в «Чистилище», я хочу дополнить информацию
				</label>
				<input type="url" class="form-control" id="url" name="data[url]" placeholder="Адрес записи" required="required" value="<?=htmlspecialchars($data['url'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="name" class="required">ФИО</label>
				<input type="text" class="form-control" required="required" id="name" name="data[name]" value="<?=htmlspecialchars($data['name'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="dob">Дата рождения</label>
				<input type="text" class="form-control" id="dob" name="data[dob]" value="<?=htmlspecialchars($data['dob'], ENT_QUOTES, 'utf-8');?>" placeholder="дд.мм.гггг"/>
			</div>
			<div class="form-group">
				<label for="country" class="required">Страна</label>
				<input type="text" class="form-control" required="required" id="country" name="data[country]" value="<?=htmlspecialchars($data['country'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="address">Адрес</label>
				<input type="text" class="form-control" id="address" name="data[address]" value="<?=htmlspecialchars($data['address'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="phone">Номер телефона</label>
				<input type="text" class="form-control" id="phone" name="data[phone]" value="<?=htmlspecialchars($data['phone'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="desc" class="required">Описание</label>
				<textarea class="form-control" id="desc" name="data[desc]" rows="20" required="required"><?=htmlspecialchars($data['desc'], ENT_QUOTES, 'utf-8');?></textarea>
				<small class="form-text text-muted">Адреса в социальных сетях, ссылки на источники, описание преступлений</small>
			</div>
			<div class="form-group">
				<label for="comment">Примечание</label>
				<input type="text" class="form-control" id="comment" name="data[comment]" value="<?=htmlspecialchars($data['comment'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="files">Фотографии, документы</label>
				<input type="file" class="form-control-file" name="files[]" id="files" multiple="multiple"/>
				<small class="form-text text-muted">
					Можно загрузить несколько файлов. Для того, чтобы выбрать несколько файлов, удерживайте клавиши
					Shift или Ctrl при выборе файлов.<br/>
					Не загружайте файлы большого размера. Если общий размер файлов превышает 10 МБ или если вы хотите загрузить больше 10 файлов,
					пожалуйста, воспользуйтесь файлообменником и добавьте ссылки на загруженные файлы в поле Описание.
				</small>
			</div>
			<div class="form-group">
				<div class="g-recaptcha" data-sitekey="<?=$recaptcha['sitekey'];?>"></div>
			</div>

			<button class="btn btn-primary" type="submit">Отправить</button>
		</form>
	</main>
<?php require 'footer.inc'; ?>
