<?php require 'header.inc'; ?>

<?php if ($errors) : ?>
	<div class="alert alert-danger" role="alert">
<?php foreach ($errors as $error) : ?>
		<?=htmlspecialchars($error, ENT_QUOTES, 'utf-8');?><br/>
<?php endforeach; ?>
	</div>
<?php endif; ?>

	<main class="card container flex-grow-1 p-3 mb-3">
		<form method="post" action="/submit" enctype="multipart/form-data">
			<div class="form-check">
				<label class="form-check-label">
					<input class="form-check-input" type="radio" name="data[present]" id="absent" value="0" required="required"<?php if ($data['present'] === 0) : ?> checked="checked"<?php endif; ?>>
					Об'єкт <strong>відсутній</strong> в «Чистилище»
				</label>
			</div>
			<div class="form-check mb-3">
				<label class="form-check-label">
					<input class="form-check-input" type="radio" name="data[present]" id="present" value="1" required="required"<?php if ($data['present'] === 1) : ?> checked="checked"<?php endif; ?>>
					Об'єкт <strong>присутній</strong> в «Чистилище», я хочу доповнити інформацію
				</label>
				<input type="url" class="form-control" id="url" name="data[url]" placeholder="Адреса запису" required="required" value="<?=htmlspecialchars($data['url'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="name" class="required mb-0 font-weight-bold">ПІБ</label>
				<input type="text" class="form-control" required="required" id="name" name="data[name]" value="<?=htmlspecialchars($data['name'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="dob" class="mb-0">Дата народження</label>
				<input type="date" class="form-control" id="dob" name="data[dob]" value="<?=htmlspecialchars($data['dob'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="country" class="required mb-0 font-weight-bold">Країна</label>
				<input type="text" class="form-control" required="required" id="country" name="data[country]" value="<?=htmlspecialchars($data['country'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="address" class="mb-0 font-weight-bold">Адреса</label>
				<input type="text" class="form-control" id="address" name="data[address]" value="<?=htmlspecialchars($data['address'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="phone" class="mb-0 font-weight-bold">Номер телефону</label>
				<input type="text" class="form-control" id="phone" name="data[phone]" value="<?=htmlspecialchars($data['phone'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="desc" class="required mb-0 font-weight-bold">Опис</label>
				<textarea class="form-control" id="desc" name="data[desc]" rows="20" required="required"><?=htmlspecialchars($data['desc'], ENT_QUOTES, 'utf-8');?></textarea>
				<small class="form-text text-muted">Адреси в соціальних мережах, посилання на джерела, опис злочинів</small>
			</div>
			<div class="form-group">
				<label for="comment" class="mb-0 font-weight-bold">Примітка</label>
				<input type="text" class="form-control" id="comment" name="data[comment]" value="<?=htmlspecialchars($data['comment'], ENT_QUOTES, 'utf-8');?>"/>
			</div>
			<div class="form-group">
				<label for="files" class="mb-1 font-weight-bold">Фотографії, документи</label>
				<input type="file" class="form-control-file" name="files[]" id="files" multiple="multiple"/>
				<small class="form-text text-muted">
					Можна завантажити кілька файлів. Щоб вибрати кілька файлів, утримуйте клавіші Shift або Ctrl при виборі файлів.<br/>
					Не завантажуйте файли великого розміру. Якщо загальний розмір файлів перевищує 10 МБ або ви хочете завантажити більше 10 файлів,
					будь ласка, скористайтеся файлообмінником та додайте посилання на завантажені файли в поле Опис.
				</small>
			</div>
			<div class="form-group">
				<div class="g-recaptcha" data-sitekey="<?=$recaptcha['sitekey'];?>"></div>
			</div>

			<button class="btn btn-primary" type="submit">Надіслати</button>
		</form>
	</main>
<?php require 'footer.inc'; ?>
