<?php require 'header.inc'; ?>

	<main class="container flex-grow-1 py-3">
		<div class="card border-success mb-3 text-center">
			<h3 class="card-header">Сообщение отправлено</h3>
			<div class="card-body text-success">
				<p class="card-text">Если вы сделали всё правильно, запись в самое ближайшее время появится в Чистилище.</p>
				<p class="card-text"><a href="/start" class="text-primary"><strong>Добавить ещё одного</strong></a></p>
				<p class="card-text"><a href="/logout" class="text-primary">Выход</a></p>
			</div>
		</div>
	</main>

<?php require 'footer.inc'; ?>
