<?php require 'header.inc'; ?>

	<main class="container flex-grow-1 py-3">
		<div class="card border-success mb-3 text-center">
			<h3 class="card-header">Повідомлення відправлено</h3>
			<div class="card-body text-success">
				<p class="card-text">Якщо ви зробили все правильно, запис найближчим часом з'явиться в Чистилище.</p>
				<p class="card-text"><a href="/start" class="text-primary"><strong>Додати ще одного</strong></a></p>
				<p class="card-text"><a href="/logout" class="text-primary">Вихід</a></p>
			</div>
		</div>
	</main>

<?php require 'footer.inc'; ?>
