<?php require 'header.inc'; ?>

	<main class="card card-inverse card-success text-center">
		<h2 class="card-header">Сообщение отправлено</h2>
		<div class="card-block">
			<p class="card-text">Если вы сделали всё правильно, запись в самое ближайшее время появится в Чистилище.</p>
			<p class="card-text"><a href="/start" class="text-primary"><strong>Добавить ещё одного</strong></a></p>
		</div>
	</main>

<?php require 'footer.inc'; ?>
